### ISSUE TITLE
"password scope" should be "password score" ?

### ISSUE THREAD

**Issue by zinks-** [brantje/passman#104]
I'm not sure about this but I can't find the developer's email, so I'll just post it here.

In several places, there is mention of a "password scope".
example: https://github.com/brantje/passman/blob/master/templates/popup.php#L180

 Is it a typo (s/scope/score) or should it stay like that ?
thanks

**Comment by brantje** [comment]
Nice found, will edit it.

**Comment by brantje** [comment]
Fixed in https://github.com/brantje/passman/commit/808027a6129077ab64bdb98a5a565c4d8db4111d#diff-398e0529e2b7c20f0e0c20f4c5a07637R146
