### ISSUE TITLE
Support: Backup 

### ISSUE THREAD

**Issue by ib54003** [brantje/passman#106]
Hey it would also be useful if i could export a backup file of my passwords in passman. And it would also be cool if there would be an option to print all your passwords to get a print backup (which can be stored on a secret place in your house).

**Comment by brantje** [comment]
In the master branch you can already export items.
![image](https://cloud.githubusercontent.com/assets/2758767/6770767/228331ba-d0cb-11e4-8155-2e05abfe312e.png)

**Comment by brantje** [comment]
As for physical copies for passwords, that undermines the whole purpose of a password manager.
My advice: Export the items as Passman JSON, place them inside a truecrypt container on a usb stick and put that stick in a vault.
