### ISSUE TITLE
Activity report: typo in string

### ISSUE THREAD

**Issue by zinks-** [brantje/passman#107]
https://github.com/brantje/passman/blob/master/lib/activity.php#L110

I believe" %2$s ***has been revised*** %1$s to the revision of %3$s" should be "%2$s ***has revised*** %1$s to the revision of %3$s"

**Comment by zinks-** [comment]
Any update on this? Would love to know how to translate it properly.

**Comment by brantje** [comment]
Fixed with commit 26c0607
