### ISSUE TITLE
Settings not ready for standard user ?

### ISSUE THREAD

**Issue by kepon85** [brantje/passman#108]
Version : Download master branche at 01:00 PM today.

When I want to export I click "Export" and nothing happens (with keepass csv, passman csv...)

When I click it happens only this :

$ tail -f data/owncloud.log ../log/error.log  ../log/access.log  | grep -v remote
87.89.0.220 - - [07/Apr/2015:14:51:36 +0200] "GET /index.php/apps/passman/api/v1/getbytags?tags= HTTP/1.1" 200 7202 "http://cloud.zici.fr/index.php/apps/passman/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:35.0) Gecko/20100101 Firefox/35.0"

When I click to disable favicons : 
87.89.0.220 - - [07/Apr/2015:14:53:18 +0200] "POST /index.php/apps/passman/api/v1/savesettings HTTP/1.1" 403 665 "http://cloud.zici.fr/index.php/apps/passman/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:35.0) Gecko/20100101 Firefox/35.0"

Note : 403 !

If I do the same thing with admin privileges it works !

Thank's

**Comment by kepon85** [comment]
Sorry, for disable favicons it's work for "toto" user with admin privileges, but for export it's not possible with toto (with admin privileges) 
Just works with "admin user"

**Comment by brantje** [comment]
I've found the problem:
https://github.com/brantje/passman/blob/master/controller/pagecontroller.php#L103

Before, add:
```/**
   * @NoAdminRequired
   * @NoCSRFRequired
   */```

**Comment by brantje** [comment]
Fixed with commiy b3817d5
