### ISSUE TITLE
Unable to show items without password

### ISSUE THREAD

**Issue by moraus** [brantje/passman#110]
If a new item is added without the "password" filled inn, for example only "label", "Description" and a "custom field", this item will not be visible in the list after a lock/unlock of the session.
The new item still exists in the database (mysql).

How to reproduce/test;
1) Add new item with only "Label" and save
2) Lock session
3) Refresh session / unlock

Nothing to find in the standard owncloud log.

**Comment by brantje** [comment]
Good catch! Will look into it.

**Comment by brantje** [comment]
Fix is commited
