### ISSUE TITLE
passman broke

### ISSUE THREAD

**Issue by animalillo** [brantje/passman#115]
Error 	PHP 	Class 'OCP\AppFramework\Http\ContentSecurityPolicy' not found at \apps\passman\controller\pagecontroller.php#66 	2015-06-01T21:12:56+00:00 

Tested in sharing with ownCloud 7.0.2 (stable) and ownCloud 8.0.3 (stable)

**Comment by brantje** [comment]
Cuz @animalillo is too lazy to post the oc version: ownCloud 8.0.3 (stable)

**Comment by brantje** [comment]
Reset to this commit
```git reset 644709cf2dc34150eb31c8478b12ee77e54f0fc0```
Will update the stable7 asap.

**Comment by animalillo** [comment]
here is a patch if anyone needs it
https://gist.github.com/animalillo/a8e71c59083aff27e8a7

**Comment by brantje** [comment]
Introduced by: 5876bc054c24cc6d17764c4219abd23ee4e517d9

![image](https://cloud.githubusercontent.com/assets/2758767/7924162/3ea1575c-08b9-11e5-8082-c081baee4098.png)
