### ISSUE TITLE
Not Saving Edits

### ISSUE THREAD

**Issue by rharkonen** [brantje/passman#119]
I am using Passman with OwnCloud 8 and it seems to be working fine except when I need to edit something, I click save and nothing happens. I have tried to reload the page and have tried it in both Firefox & Safari.

**Comment by brantje** [comment]
What version are you using?
The one from the app store or master branch?

**Comment by rharkonen** [comment]
I am using the one from the app store.

**Comment by brantje** [comment]
Ahh yea, master is developed against the ownCloud master, and therefore a little experimental.
Just a sec, i give you a working commit that you can checkout.

**Comment by brantje** [comment]
```
git clone https://github.com/brantje/passman
cd passman
git reset --hard 644709cf2dc34150eb31c8478b12ee77e54f0fc0
```

**Comment by rharkonen** [comment]
That seems to have fixed it! Thanks
