### ISSUE TITLE
Create API for external apps

### ISSUE THREAD

**Issue by brantje** [brantje/passman#12]
For firefox sync, chrome sync etc.

**Comment by 1234Georg** [comment]
I thought about writing an smart phone app for passman.
Is this a good idea? Can I use the API you already wrote?

**Comment by brantje** [comment]
Hi @1234Georg 
Yea you can use the current api, i know its little bit of a mess.

I need time to refactor the API, but that will cost time and thats something thats rare for me -_-.
If you have idea's / suggestions for the API let me know.

**Comment by brantje** [comment]
Fixed [in the NexCloud repo](https://github.com/nextcloud/passman)
