### ISSUE TITLE
MySQL 5.7: GROUP BY incompatible

### ISSUE THREAD

**Issue by moraus** [brantje/passman#135]
### Steps to reproduce
1.   Install / upgrade mysql (Follows with ubuntu 16.04)
2.   Run the application

Apparently mysql 5.7 changes the behavior of GROUP BY. More info: http://rpbouman.blogspot.no/2014/09/mysql-575-group-by-respects-functional.html
  
### Expected behaviour
Normal "log in" / unlocking the passman app

### Actual behaviour
Continuous spinning wheel

### Server configuration
**Operating system**: Ubuntu 16.04

**Web server:** Apache2 (2.4.18)

**Database:** mysql (5.7.12)

**PHP version:** 7.0.4

**ownCloud version:** 9.0.1

**Updated from an older ownCloud or fresh install:**
Updated from older version

### Client configuration
**Browser:**
Firefox 46

**Operating system:**
Ubuntu 16.04

#### Web server error log
No error

#### ownCloud log (data/owncloud.log)
{"reqId":"JG4DUBaZHarMjyCKU4Bj","remoteAddr":"84.16.211.225","app":"index","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\DriverException\",\"Message\":\"An exception occurred while executing 'SELECT  item.id, LOWER(GROUP_CONCAT(distinct tags.tag_label)) AS tagForSearch ,GROUP_CONCAT(distinct tags.tag_label) AS tags FROM `oc_passman_items` AS item LEFT JOIN `oc_passman_items_tags_xref` AS xref ON xref.item_id = item.id LEFT JOIN `oc_passman_tags` AS tags ON tags.tag_id = xref.tag_id WHERE item.user_id=? AND delete_date =0 GROUP BY item.id  ORDER BY UPPER(item.label) ASC, tags.tag_label ASC' with params [\\\"moraus\\\"]:\\n\\nSQLSTATE[42000]: Syntax error or access violation: 1055 Expression #2 of ORDER BY clause is not in GROUP BY clause and contains nonaggregated column 'owncloud.tags.tag_label' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(116): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Statement.php(174): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'SELECT  item.id...', Array)\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/db\\\/statementwrapper.php(73): Doctrine\\\\DBAL\\\\Statement->execute(Array)\\n#3 \\\/var\\\/www\\\/owncloud\\\/apps_user\\\/passman\\\/db\\\/itemmanager.php(95): OC_DB_StatementWrapper->execute(Array)\\n#4 \\\/var\\\/www\\\/owncloud\\\/apps_user\\\/passman\\\/businesslayer\\\/itembusinesslayer.php(46): OCA\\\\Passman\\\\Db\\\\ItemManager->getByTag(Array, Array, false)\\n#5 \\\/var\\\/www\\\/owncloud\\\/apps_user\\\/passman\\\/controller\\\/itemapicontroller.php(91): OCA\\\\Passman\\\\BusinessLayer\\\\ItemBusinessLayer->getByTag(Array, 'moraus', false)\\n#6 [internal function]: OCA\\\\Passman\\\\Controller\\\\ItemApiController->getbytag(NULL, false)\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(159): call_user_func_array(Array, Array)\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Passman\\\\Controller\\\\ItemApiController), 'getbytag')\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/app.php(110): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Passman\\\\Controller\\\\ItemApiController), 'getbytag')\\n#10 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/routing\\\/routeactionhandler.php(45): OC\\\\AppFramework\\\\App::main('ItemApiControll...', 'getbytag', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#11 [internal function]: OC\\\\AppFramework\\\\routing\\\\RouteActionHandler->__invoke(Array)\\n#12 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(276): call_user_func(Object(OC\\\\AppFramework\\\\routing\\\\RouteActionHandler), Array)\\n#13 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(882): OC\\\\Route\\\\Router->match('\\\/apps\\\/passman\\\/a...')\\n#14 \\\/var\\\/www\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#15 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractMySQLDriver.php\",\"Line\":115}","level":3,"time":"2016-05-04T13:02:11+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/passman\/api\/v1\/getbytags?tags=","user":"moraus"}

**Comment by brantje** [comment]
Fixed [in the NexCloud repo](https://github.com/nextcloud/passman)
