### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by brantje** [brantje/passman#14]
Add translation support
http://doc.owncloud.org/server/7.0/developer_manual/app/l10n.html

**Comment by Sugaroverdose** [comment]
Translation of plurals should support plural forms, languages like Russian have 3 or more (Irish have 6) plural forms, so app cannot be correctly translated with single string(which i see now on transifex). l10n and transifex does support plural forms.
So you only need to replace single string translation like 
<option value="15">15 <?php p($l->t('Minutes')); ?></option> 
With plural form translation 
<option value="15"><?php p($l->n(%n Minute','%n Minutes',15)); ?></option> 

As primer (en = ru):
1 day = 1 день
2 days = 2 дня
5 days = 5 дней

**Comment by brantje** [comment]
Thanks for your input, will edit the strings. And push back to master.

**Comment by brantje** [comment]
Closing, translations are implemented in master.
Passman uses Transifex for the translations.
https://www.transifex.com/projects/p/owncloud/resource/passman/

**Comment by Sugaroverdose** [comment]
@brantje somehow '%n hours' registered as common string, not plural
![2015-01-18 11 30 32 pm](https://cloud.githubusercontent.com/assets/10269200/5793945/1f06f900-9f6a-11e4-8693-45a9656122b4.png)

**Comment by brantje** [comment]
Will look into it later this week

**Comment by brantje** [comment]
Fixed withhttps://github.com/brantje/passman/commit/b36581d534c09f7d45a37e8ca1b81299a1f57107
