### ISSUE TITLE
Password sharing

### ISSUE THREAD

**Issue by brantje** [brantje/passman#57]
For example:
User A shares a password with user b.
User a changes the password, does user b has the changed password?
   
User A shares a password with user b.
User b changes the password, does user a has the changed password?

How to notify when a password is shared? There is not an notification center in ownCloud.
I might build this for ownCloud, but then it has to be a core app.

Technical obstructions:
The passwords are client-side encrypted, and the key phrase is not known at the server.
So how can i update the password for (eg user b)  when (eg user a) changes the password?
If this obstacle can be overcome, then password sharing is a possibility.

**Comment by animalillo** [comment]
https://github.com/travist/jsencrypt

**Comment by animalillo** [comment]
Specified in the todo list for the V2 (#56)

**Comment by brantje** [comment]
Closing issue as @animalillo is going to fix this ^_^.
