### ISSUE TITLE
Syntax error or access violation

### ISSUE THREAD

**Issue by Salzi** [brantje/passman#65]
After updating to owncloud 7.0.3 I tried to install the current git version (master). During the update I got the message:

An exception occurred while executing 'DROP INDEX items_tags_tag_id ON `oc_oc_passman_tags_019f01cc41945`': SQLSTATE[42000]: Syntax error or access violation: 1075 Incorrect table definition; there can be only one auto column and it must be defined as a key

**Comment by brantje** [comment]
Closing issue, seems to be resolved in master branch.
