### ISSUE TITLE
Passman events

### ISSUE THREAD

**Issue by brantje** [brantje/passman#75]
item_created  => When an item is created
item_edited => When an item is edited
item_apply_revision => When an revision is put back
item_deleted => When an item is soft deleted
item_recovered => When an item is recovered
item_destroyed => When an item is hard deleted
item_expired => When an password for an item expires
item_shared => When an item is shared with group / user

Adding an event
===
Inject the notificatiocontroller, then:
As example we use an empty controller:
``
private $notification;
public function __construct($appName,$notificationController){
    $this->notification = $notificationController;
}
``

Example:
`` $this->notification->add('item_created',array($item['label'],$userId));``

**Comment by animalillo** [comment]
nice, will use them soon, i hope

**Comment by brantje** [comment]
Deprecated, will post an updated version soon.
